modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]]
modId="bringbackbedrock" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Bring Back Bedrock" #mandatory
logoFile="logo.png" #optional
credits="Thanks Forge and NeoForge for their example mod" #optional
authors="JayJay1989BE, Darkosto" #optional
description='''
Restores the bedrock layer where needed
'''

[[dependencies.bringbackbedrock]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bringbackbedrock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
